### ISSUE TITLE
rebuild after a destroy, issues related to secret manager

### ISSUE THREAD

**Issue by chris-mackubin** [bluesentry/tf-module.keypair#7]
This module currently stores the keypair pem file into the Secrets Manager.  If Terraform -destory is ran and then a subsequent re-apply, an error will occur related to this secret.  The issue is that secrets are not deleted as Secret Manager doesn't allow this.  Instead the secret is marked for deletion.  When an attempt is made to re-apply and recreate the secret, an error occurs as the secret with that name already exists. 

`InvalidRequestException: You can't create this secret because a secret with this name is already scheduled for deletion.`

---
One thought on this is in the provider, there could be logic to have the provider call `RestoreSecret` api which is available in the `aws-sdk-go`.  

For a quick fix, we could add a few random chars to the end of the secret name making it unique.

**Comment by denniswebb** [comment]
Fixed by #9
